# Spring Boot Application Configuration
server.port=8080
spring.application.name=SecureDataSharing

# Static Resources
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=3600

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
